### PR TITLE
 SW-319. improve iotlab support

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR adds support for `iotlab-a8-m3` boards usage. It also adds a XonXoff implementation for iotlab access.

Some fixes have been added in this PR as well:

- gracefully ignore invalid --root node 2b7f7ab
- handle forced exit during openv-serial, run as script as well as adding iotlab support
51a4c6b
- if not all bytes are written attempt to send only the ones missing cdfc2c8

`serialtester` still works on an `opnemote-b`

```
python tests/scripts/serialtester_cli.py 
Serial Tester Script...

Test Setup:
----------------
Iterations:    100
Packet length: 100
Echo timeout:    2

Test Progress:

  [####################################]  100%          


Test Statistics:
----------------
Pkts send:      100
Echo success:   100
Echo timeout:     0
Echo corrupted:   0

exiting...
```

Can now connect to a8-m3

```
openv-server --iotlab-motes a8-100.saclay.iot-lab.info m3-101.grenoble.iot-lab.info --baudrate=500000

 ___                 _ _ _  ___  _ _ 
| . | ___  ___ ._ _ | | | |/ __>| \ |
| | || . \/ ._>| ' || | | |\__ \|   |
`___'|  _/\___.|_|_||__/_/ <___/|_\_|
     |_|                  openwsn.org

10:37:20 [OpenVisualizerServer:VERBOSE] Loading logging configuration: config/logging.conf
10:37:20 [OpenVisualizerServer:INFO] Initializing OV Server with options:
	- host address server     = localhost
	- port number server      = 9000
	- firmware path           = /home/francisco/workspace/openwsn/openwsn-fw-riot/
	- use page zero           = False
	- use VCD logger          = False
	- baudrates to probe      = ['500000']
10:37:22 [MoteProbe:SUCCESS] a8-100.saclay.iot-lab.info Ok.
10:37:23 [MoteProbe:SUCCESS] m3-101.grenoble.iot-lab.info Ok.
10:37:23 [MoteProbe:SUCCESS] Discovered following iotlab-motes: ['a8-100.saclay.iot-lab.info', 'm3-101.grenoble.iot-lab.info']
10:37:23 [OpenVisualizerServer:INFO] Extracting firmware definitions.
10:37:23 [Utils:VERBOSE] Extracting firmware component names
10:37:23 [Utils:VERBOSE] Extracting firmware log descriptions.
10:37:23 [Utils:VERBOSE] Extracting 6top return codes.
10:37:23 [Utils:VERBOSE] Extracting 6top states.
10:37:23 [OpenVisualizerServer:INFO] Starting RPC server
^C10:37:27 [MoteProbe:WARNING] a8-100.saclay.iot-lab.info; exit loop
10:37:27 [MoteProbe:WARNING] m3-101.grenoble.iot-lab.info; exit loop
```

### CODE REVIEW

**Comment by fjmolinas** [comment]
Maybe @TimothyClaeys can review?

**Comment by TimothyClaeys** [comment]
@fjmolinas I moved the scripts folder to the root of the project instead of having them inside the openvisualizer package. Could you rebase this PR?

**Comment by fjmolinas** [comment]
Rebasing and verifying that everything is still ok...

**Comment by fjmolinas** [comment]
I found a bug in the A8 integration when rebasing, don't have the right fix yet.

**Comment by TimothyClaeys** [comment]
no worries!

**Comment by fjmolinas** [comment]
I've realized that the approach I took for the iotlab-a8 is flawed, I'll have to refactor and implement a completely different approach. I'll re-open when I have something.

**Pull request closed without merging**
