### PR TITLE
SW-320. Move scripts to pkg directory

### PR DESCRIPTION
**Pull request by fjmolinas**
When installing with `pip install .` I can't run `openv-serial`, this PR moves the scripts to the pk directory to allow it:

- before PR

```
 openv-serial
openv-serial: command not found
```

- with PR

```
openv-serial /dev/riot/tty-openmote-b
Serial Tester Script...

Test Setup:
----------------
Iterations:    100
Packet length: 100
Echo timeout:    2

Test Progress:

  [####################################]  100%          


Test Statistics:
----------------
Pkts send:      100
Echo success:   100
Echo timeout:     0
Echo corrupted:   0

Kill with Ctrl-C.

```

### CODE REVIEW

**Comment by fjmolinas** [comment]
Maybe @TimothyClaeys can test?

**Comment by fjmolinas** [comment]
Ups wrong issue tag in commit

**Comment by TimothyClaeys** [comment]
Looking good, merging now!

**Comment by fjmolinas** [comment]
@TimothyClaeys https://openwsn.atlassian.net/jira/software/c/projects/SW/issues/SW-320 can be closed now.

**Pull request merged**
